### ISSUE TITLE
possible duplication when adding new albums ?

### ISSUE THREAD

**Issue by xtj-9182** [garretyoder/Cluttr#4]
I have 2 folders; name0 and name1. When I start cluttr I see this:

09-11 17:21:22.260 13634-13669/org.polaric.cluttr D/Cluttr: New album found: name0, adding to cache
09-11 17:21:22.268 13634-13672/org.polaric.cluttr D/Cluttr: New album found: name0, adding to cache
09-11 17:21:22.313 13634-13669/org.polaric.cluttr D/Cluttr: Reloading all cover photos took 20
09-11 17:21:22.320 13634-13672/org.polaric.cluttr D/Cluttr: Reloading all cover photos took 11
09-11 17:21:22.349 13634-13669/org.polaric.cluttr D/Cluttr: New album found: name1, adding to cache
09-11 17:21:22.356 13634-13672/org.polaric.cluttr D/Cluttr: New album found: name1, adding to cache
09-11 17:21:22.585 13634-13669/org.polaric.cluttr D/Cluttr: Reloading all cover photos took 78
09-11 17:21:22.596 13634-13672/org.polaric.cluttr D/Cluttr: Reloading all cover photos took 31

to me this looks like something is done twice even though it should only be done once.

**Comment by garretyoder** [comment]
Most likely Cluttr's doing what it's supposed to do, which is do a initial scan when it loads, and then a more thorough scan when it notices any filesystem changes, though I'll look into it.
